NAME        = fixed

CC          = c++
FLAGS       = -Wall -Wextra -Werror -std=c++98

SRCS        = main.cpp Fixed.cpp
OBJS        = $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(FLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp Fixed.hpp
	$(CC) $(FLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

run: all clean
	@clear
	@./$(NAME)
	@rm $(NAME)

.PHONY: all clean fclean re